### ISSUE TITLE
ruby/3.0.0 isn't supported by this pry-doc version

### ISSUE THREAD

**Issue by ninp0** [pry/pry-doc#106]
Please provide support for Ruby 3.0.0 at your earliest convenience.  Thanks.

**Comment by stouset** [comment]
Will this be released soon?

**Comment by kyrylo** [comment]
Looks like tests are failing on Ruby 3.0 https://github.com/pry/pry-doc/pull/109

We depend on YARD to retrieve docs: https://github.com/lsegal/yard

I can see that the YARD website doesn't have docs for 3.0. At the time of writing `core` points to 2.7.0: https://rubydoc.info/stdlib/core

It may be a YARD issue. Someone needs to investigate.

**Comment by quentindemetz** [comment]
Looks like YARD added support for ruby 3 last May (see https://github.com/lsegal/yard/commits/main). There hasn't been a release since December 2020 though.
