### ISSUE TITLE
Error: Cannot locate this method: xxxxxxx . Try 'gem-install pry-doc' to get access..

### ISSUE THREAD

**Issue by alankis** [pry/pry-doc#33]
I have installed pry and pry-doc, but I can't access any documentation. yard gem is also installed, and finally am I using rbenv as Ruby version manager. I can't load or access documentation from other project folders, but I can from location where pry gem is installed which is in my case:

'/home/alan/.rbenv/shims/

My setup is like this:

```
rbenv 1.0.0-19-g29b4da7
rbenv 1.0.0-19-g29b4da7
```

And output of 'gem list | grep pry' is bellow:

```
pry (0.10.3)
pry-doc (0.8.0)
```

'gem list | grep yard' 
`yard (0.8.7.6)`

Thanks, Alan

**Comment by dgutov** [comment]
> I can't load or access documentation from other project folders

What have you tried exactly, and how do the results look?

`? puts` seems to work okay here even using Ruby 2.3.0, mostly because https://github.com/pry/pry-doc/commit/04081052c83d7fb84f8e70b3a7547fa3e7ec061f is not in any released version of pry-doc.

**Comment by quixotically** [comment]
`require 'pry-doc'`
in the pry session worked for me.

More details:
I had this issue as well, after just having done a fresh gem install of pry and pry-doc.

![Screenshot from 2021-04-14 16-58-14](https://user-images.githubusercontent.com/11359452/114786213-5c30be00-9d43-11eb-86d2-0edc1d1bf97c.png)

Luckily from [this reddit post](https://www.reddit.com/r/ruby/comments/m11lms/how_to_fix_invoke_the_geminstall_prydoc_pry/gqbfefi?utm_source=share&utm_medium=web2x&context=3) I tried the solution I mentioned and it worked.

**Comment by andrehjr** [comment]
Having an updated pry-doc and calling `require 'pry-doc'` should just work.
