### ISSUE TITLE
Support Ruby 2.4

### ISSUE THREAD

**Issue by dgubitsky** [pry/pry-doc#44]
The error message under Ruby 2.4 is "Ruby 2.4.0 isn't supported by this pry-doc version"

**Comment by kyrylo** [comment]
Fixed by https://github.com/pry/pry-doc/pull/46. Expect a new release this year.

**Comment by kyrylo** [comment]
Just released pry-doc (0.10.0). Happy doc browsing and happy New Year, of course 🎄
