### ISSUE TITLE
Next version with support ruby 2.5.0?

### ISSUE THREAD

**Issue by paulomcnally** [pry/pry-doc#78]
Hi, when are you planning to launch the new version with ruby 2.5.0 support?

Thanks

**Comment by banister** [comment]
Out of interest what doesn't work on 2.5.0? I have it working locally

**Comment by banister** [comment]
@paulomcnally ping

**Comment by banister** [comment]
Sorry I thought this was the pry not pry doc repo 😓

**Comment by paulomcnally** [comment]
`ruby/2.5.0 isn't supported by this pry-doc version`

**Comment by banister** [comment]
Supported
